name: Ingest log
on:
  repository_dispatch:
    types: [log_event]
permissions:
  contents: write
jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Append entry
        run: node scripts/append-log.js
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/log.json
          git commit -m "log: append" || exit 0
          git push


